const types = {
  ADD_TAB: 'ADD_TAB',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_TASK_STATUS: 'CHANGE_TASK_STATUS',
  RESET_LIST: 'RESET_LIST',
  COPY_LIST: 'COPY_LIST',
  EDIT_TAB: 'EDIT_TAB',
  ADD_TO_HISTORY: 'ADD_TO_HISTORY',
  DELETE_TAB:'DELETE_TAB'
};

export default types;
